# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-alpine

WORKDIR /app

# Install build dependencies
RUN apk add --no-cache gcc musl-dev libffi-dev openssl-dev

# Copy source code
COPY . .

# Upgrade pip and install package dependencies
RUN pip install --upgrade pip \
    && pip install .

# Set environment variables for runtime, if not provided, will be overridden by Smithery config
ENV SPLUNKBASE_USERNAME=demo_user
ENV SPLUNKBASE_PASSWORD=demo_pass

CMD ["python", "splunkbase-mcp.py"]
